trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: gradle --init-script gradle/support/fetchDependencies.gradle init
  displayName: 'Init flat directory-style repository'

- task: Gradle@2
  displayName: 'gradlew buildGhidra'
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: ''
    tasks: buildGhidra
    jdkVersionOption: 1.11