schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
jobs:
  - job: Instructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        persistCredentials: true
      - script: |
          git remote -v
          git remote add upstream https://github.com/NationalSecurityAgency/ghidra
          git fetch upstream master
          git fetch origin master
          git checkout origin/master
          git checkout -b temp_master
          git merge upstream/master --ff-only
          git push origin HEAD:master
          git checkout origin/master
          git branch -D temp_master
        displayName: 'Update master from upstream'
